# Site settings
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "petsit.io"
baseurl = "https://petsit.io/"
#theme = "hugo-agency-theme"
paginate = 10
# Enter your tracking code to enable Google Analytics
googleAnalytics = "G-ES3M0G4406"

[markup.goldmark.renderer]
  unsafe= true

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[params]
  title = "petsit.io"
  site_author = "Marc Cohen"
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at 
  # fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "petsit.io"
    # Optional logo as brand stored in img/
    #logo = "petsit.png"
    mission = "Mission"
    services = "Services"
    team = "About"
    portfolio = "Gallery"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
      #url = "http://gohugo.io"
      #name = "External link"
      #weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "petsit.io"
    subtitle = "Loving and Reliable Petsitting Service"
    buttonText = "Tell me more"

  # Mission section
  [params.mission]
    # To change the background image of the mission, replace 'mission.jpg' in
    # the 'static/img' folder.
    enable = true
    title = "Mission"
    subtitle = """
<span style="font-size: 24px">
My mission is to provide your beloved friend with a wonderful time and deliver you peace of mind. I focus on small group walks of a maximum of three dogs at time. I also offer private walks.
</span>
"""

  # Services section
  [params.services]
    enable = true
    title = "Services"

    [[params.services.row]]

      url = "#"

#    [[params.services.row.list]]
#      icon = "fa-gbp"
#      title = "Fees"
#      description = """
#<ul style="text-align:left">
#<li>Dog walking : from £12 per 30 minute solo walk</li>
#<li>Dog sitting: from £25</li>
#<li>Dog live in: from £40 per day, £12 for additional dog
#<li>Dog boarding: from £ 38, £12 for additional dog
#<li>Cat sitting: regular 30 minute visit from £12; two regular visits per day from £22 per day; longer visits ( at least one hour) £19 and £37 respectively.</li>
#</ul>
#"""
#      url = "#"

    [[params.services.row.list]]
      icon = "fa-paw"
      title = "Services"
      description = """
<ul style="text-align:left">
<li>Dog walking, dog sitting with live in if required</li>
<li>Cat feed & play, cat live in</li>
<li>Home visits available for bathroom breaks, medication, feeding and company (contact me to enquire)</li>
</ul>
                    """
      url = "#"

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    center = true
    title = "About Romi"
    subtitle = ""
    description = """
<span style="font-size: 20px">
I am an experienced cat and dog walker/sitter. I look after my four legged clients as if they are my own. I live in Camden and would be happy to help if you live  in Hampstead, Belize Park, Kentish Town, Primrose Hill, Camden Town, Gospel Oak, South End Green, Highgate, St.Johns Wood or Crouch End. For your peace of mind, I am DBS checked and can provide additional references.
</span>
      """

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "romi-clyro.jpg"

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Gallery"
    subtitle = "Some of my best friends..."
    category = "Category"

    [params.portfolio.modal]
      title = "Gallery"
      subtitle = "Some of my best friends (human and canine)..."
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      center = true
      # Optional client title specifying the involvement
      title = "Testimonials"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good

  # Contact section
  [params.contact]
    enable = true
    headline= "Contact Me"
    description = " "
    buttonText = "Send message"
    phone = "(0)7809 114766"
    email = "romciamaria@gmail.com"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    # email = "romciamaria@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Thank you for contacting me."
    error = "Message could not be sent. Please contact me at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = false
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
